[package]
name = "bitcoin-blockhash-calc"
version = "0.1.0"
authors = ["Vladimir Vasquez <vvmaster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
ring = "0.16.9"